# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mod_presupuesto_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class modPresupuestoWindow(object):
    def setupUi(self, modPresupuestoWindow):
        if not modPresupuestoWindow.objectName():
            modPresupuestoWindow.setObjectName(u"modPresupuestoWindow")
        modPresupuestoWindow.resize(751, 619)
        self.label = QLabel(modPresupuestoWindow)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 731, 20))
        self.label.setFrameShape(QFrame.Box)
        self.frame = QFrame(modPresupuestoWindow)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 50, 731, 111))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(340, 10, 111, 16))
        self.presupuestoEmiModDateEdit = QDateEdit(self.frame)
        self.presupuestoEmiModDateEdit.setObjectName(u"presupuestoEmiModDateEdit")
        self.presupuestoEmiModDateEdit.setGeometry(QRect(340, 30, 110, 22))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(500, 10, 111, 16))
        self.presupuestoVencModDateEdit = QDateEdit(self.frame)
        self.presupuestoVencModDateEdit.setObjectName(u"presupuestoVencModDateEdit")
        self.presupuestoVencModDateEdit.setGeometry(QRect(500, 30, 110, 22))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 101, 16))
        self.presupuestoNroModlineEdit = QLineEdit(self.frame)
        self.presupuestoNroModlineEdit.setObjectName(u"presupuestoNroModlineEdit")
        self.presupuestoNroModlineEdit.setGeometry(QRect(10, 30, 131, 20))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 61, 16))
        self.presupuestoClienteModComboBox = QComboBox(self.frame)
        self.presupuestoClienteModComboBox.setObjectName(u"presupuestoClienteModComboBox")
        self.presupuestoClienteModComboBox.setGeometry(QRect(10, 80, 561, 22))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(170, 10, 121, 16))
        self.presupuestoTasaModLineEdit = QLineEdit(self.frame)
        self.presupuestoTasaModLineEdit.setObjectName(u"presupuestoTasaModLineEdit")
        self.presupuestoTasaModLineEdit.setGeometry(QRect(170, 30, 141, 20))
        self.frame_2 = QFrame(modPresupuestoWindow)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 170, 731, 80))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 121, 16))
        self.presupuestoTipoModComboBox = QComboBox(self.frame_2)
        self.presupuestoTipoModComboBox.setObjectName(u"presupuestoTipoModComboBox")
        self.presupuestoTipoModComboBox.setGeometry(QRect(10, 40, 111, 22))
        self.presupuestoProdServModComboBox = QComboBox(self.frame_2)
        self.presupuestoProdServModComboBox.setObjectName(u"presupuestoProdServModComboBox")
        self.presupuestoProdServModComboBox.setGeometry(QRect(130, 40, 441, 22))
        self.presupuestoCantModLineEdit = QLineEdit(self.frame_2)
        self.presupuestoCantModLineEdit.setObjectName(u"presupuestoCantModLineEdit")
        self.presupuestoCantModLineEdit.setGeometry(QRect(580, 40, 81, 20))
        self.presupuestoModAddPushButton = QPushButton(self.frame_2)
        self.presupuestoModAddPushButton.setObjectName(u"presupuestoModAddPushButton")
        self.presupuestoModAddPushButton.setGeometry(QRect(670, 40, 25, 25))
        icon = QIcon()
        icon.addFile(u"./assets/icons/botones/agregar_item.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoModAddPushButton.setIcon(icon)
        self.presupuestoModAddPushButton.setIconSize(QSize(24, 24))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(580, 20, 47, 13))
        self.presupuestoModElimPushButton = QPushButton(self.frame_2)
        self.presupuestoModElimPushButton.setObjectName(u"presupuestoModElimPushButton")
        self.presupuestoModElimPushButton.setGeometry(QRect(700, 40, 25, 25))
        icon1 = QIcon()
        icon1.addFile(u"./assets/icons/botones/eliminar_item.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoModElimPushButton.setIcon(icon1)
        self.presupuestoModElimPushButton.setIconSize(QSize(24, 24))
        self.frame_3 = QFrame(modPresupuestoWindow)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 260, 731, 281))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.presupuestoModTableWidget = QTableWidget(self.frame_3)
        self.presupuestoModTableWidget.setObjectName(u"presupuestoModTableWidget")
        self.presupuestoModTableWidget.setGeometry(QRect(10, 10, 711, 261))
        self.label_8 = QLabel(modPresupuestoWindow)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 550, 101, 16))
        self.label_9 = QLabel(modPresupuestoWindow)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 550, 111, 16))
        self.label_10 = QLabel(modPresupuestoWindow)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(450, 550, 271, 16))
        self.presupuestoAceptarModPushButton = QPushButton(modPresupuestoWindow)
        self.presupuestoAceptarModPushButton.setObjectName(u"presupuestoAceptarModPushButton")
        self.presupuestoAceptarModPushButton.setGeometry(QRect(210, 590, 101, 23))
        icon2 = QIcon()
        icon2.addFile(u"./assets/icons/botones/modificar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoAceptarModPushButton.setIcon(icon2)
        self.presupuestoCancelarModPushButton = QPushButton(modPresupuestoWindow)
        self.presupuestoCancelarModPushButton.setObjectName(u"presupuestoCancelarModPushButton")
        self.presupuestoCancelarModPushButton.setGeometry(QRect(350, 590, 101, 23))
        icon3 = QIcon()
        icon3.addFile(u"./assets/icons/botones/cancelar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoCancelarModPushButton.setIcon(icon3)
        self.presupuestoTotDolarModLineEdit = QLineEdit(modPresupuestoWindow)
        self.presupuestoTotDolarModLineEdit.setObjectName(u"presupuestoTotDolarModLineEdit")
        self.presupuestoTotDolarModLineEdit.setEnabled(True)
        self.presupuestoTotDolarModLineEdit.setGeometry(QRect(120, 550, 171, 20))
        self.presupuestoTotDolarModLineEdit.setReadOnly(True)
        self.presupuestoTotBsModLineEdit = QLineEdit(modPresupuestoWindow)
        self.presupuestoTotBsModLineEdit.setObjectName(u"presupuestoTotBsModLineEdit")
        self.presupuestoTotBsModLineEdit.setEnabled(True)
        self.presupuestoTotBsModLineEdit.setGeometry(QRect(450, 550, 171, 20))
        self.presupuestoTotBsModLineEdit.setReadOnly(True)

        self.retranslateUi(modPresupuestoWindow)

        QMetaObject.connectSlotsByName(modPresupuestoWindow)
    # setupUi

    def retranslateUi(self, modPresupuestoWindow):
        modPresupuestoWindow.setWindowTitle(QCoreApplication.translate("modPresupuestoWindow", u"Modificar Presupuesto", None))
        self.label.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">MODIFICAR PRESUPUESTO</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Fecha de Emisi\u00f3n:</p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Fecha de Vencimiento:</p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Nro. Presupuesto:</p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Cliente:</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Tasa a Utilizar (Bs):</p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Productos / Servicios:</p></body></html>", None))
        self.presupuestoModAddPushButton.setText("")
        self.label_11.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p>Cantidad:</p></body></html>", None))
        self.presupuestoModElimPushButton.setText("")
        self.label_8.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Total Dolares:</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Total Bol\u00edvares:</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("modPresupuestoWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.presupuestoAceptarModPushButton.setText(QCoreApplication.translate("modPresupuestoWindow", u"Modificar", None))
        self.presupuestoCancelarModPushButton.setText(QCoreApplication.translate("modPresupuestoWindow", u" Cancelar", None))
    # retranslateUi

