# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'nuevo_presupuesto_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class nuevoPresupuestoWindow(object):
    def setupUi(self, nuevoPresupuestoWindow):
        if not nuevoPresupuestoWindow.objectName():
            nuevoPresupuestoWindow.setObjectName(u"nuevoPresupuestoWindow")
        nuevoPresupuestoWindow.resize(751, 619)
        self.label = QLabel(nuevoPresupuestoWindow)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 731, 20))
        self.label.setFrameShape(QFrame.Box)
        self.frame = QFrame(nuevoPresupuestoWindow)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 50, 731, 111))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(340, 10, 111, 16))
        self.presupuestoEmiRegDateEdit = QDateEdit(self.frame)
        self.presupuestoEmiRegDateEdit.setObjectName(u"presupuestoEmiRegDateEdit")
        self.presupuestoEmiRegDateEdit.setGeometry(QRect(340, 30, 110, 22))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(500, 10, 111, 16))
        self.presupuestoVencRegDateEdit = QDateEdit(self.frame)
        self.presupuestoVencRegDateEdit.setObjectName(u"presupuestoVencRegDateEdit")
        self.presupuestoVencRegDateEdit.setGeometry(QRect(500, 30, 110, 22))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 101, 16))
        self.presupuestoNroReglineEdit = QLineEdit(self.frame)
        self.presupuestoNroReglineEdit.setObjectName(u"presupuestoNroReglineEdit")
        self.presupuestoNroReglineEdit.setGeometry(QRect(10, 30, 131, 20))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 61, 16))
        self.presupuestoClienteRegComboBox = QComboBox(self.frame)
        self.presupuestoClienteRegComboBox.setObjectName(u"presupuestoClienteRegComboBox")
        self.presupuestoClienteRegComboBox.setGeometry(QRect(10, 80, 561, 22))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(170, 10, 121, 16))
        self.presupuestoTasaRegLineEdit = QLineEdit(self.frame)
        self.presupuestoTasaRegLineEdit.setObjectName(u"presupuestoTasaRegLineEdit")
        self.presupuestoTasaRegLineEdit.setGeometry(QRect(170, 30, 141, 20))
        self.frame_2 = QFrame(nuevoPresupuestoWindow)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 170, 731, 80))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 121, 16))
        self.presupuestoTipoRegComboBox = QComboBox(self.frame_2)
        self.presupuestoTipoRegComboBox.setObjectName(u"presupuestoTipoRegComboBox")
        self.presupuestoTipoRegComboBox.setGeometry(QRect(10, 40, 111, 22))
        self.presupuestoProdServRegComboBox = QComboBox(self.frame_2)
        self.presupuestoProdServRegComboBox.setObjectName(u"presupuestoProdServRegComboBox")
        self.presupuestoProdServRegComboBox.setGeometry(QRect(130, 40, 441, 22))
        self.presupuestoCantRegLineEdit = QLineEdit(self.frame_2)
        self.presupuestoCantRegLineEdit.setObjectName(u"presupuestoCantRegLineEdit")
        self.presupuestoCantRegLineEdit.setGeometry(QRect(580, 40, 81, 20))
        self.presupuestoNuevoAddPushButton = QPushButton(self.frame_2)
        self.presupuestoNuevoAddPushButton.setObjectName(u"presupuestoNuevoAddPushButton")
        self.presupuestoNuevoAddPushButton.setGeometry(QRect(670, 40, 25, 25))
        icon = QIcon()
        icon.addFile(u"./assets/icons/botones/agregar_item.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoNuevoAddPushButton.setIcon(icon)
        self.presupuestoNuevoAddPushButton.setIconSize(QSize(24, 24))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(580, 20, 47, 13))
        self.presupuestoNuevoElimPushButton = QPushButton(self.frame_2)
        self.presupuestoNuevoElimPushButton.setObjectName(u"presupuestoNuevoElimPushButton")
        self.presupuestoNuevoElimPushButton.setGeometry(QRect(700, 40, 25, 25))
        icon1 = QIcon()
        icon1.addFile(u"./assets/icons/botones/eliminar_item.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoNuevoElimPushButton.setIcon(icon1)
        self.presupuestoNuevoElimPushButton.setIconSize(QSize(24, 24))
        self.frame_3 = QFrame(nuevoPresupuestoWindow)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 260, 731, 281))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.presupuestoRegTableWidget = QTableWidget(self.frame_3)
        self.presupuestoRegTableWidget.setObjectName(u"presupuestoRegTableWidget")
        self.presupuestoRegTableWidget.setGeometry(QRect(10, 10, 711, 261))
        self.label_8 = QLabel(nuevoPresupuestoWindow)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 550, 101, 16))
        self.label_9 = QLabel(nuevoPresupuestoWindow)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 550, 111, 16))
        self.label_10 = QLabel(nuevoPresupuestoWindow)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(450, 550, 271, 16))
        self.presupuestoAceptarRegPushButton = QPushButton(nuevoPresupuestoWindow)
        self.presupuestoAceptarRegPushButton.setObjectName(u"presupuestoAceptarRegPushButton")
        self.presupuestoAceptarRegPushButton.setGeometry(QRect(210, 590, 101, 23))
        icon2 = QIcon()
        icon2.addFile(u"./assets/icons/botones/agregar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoAceptarRegPushButton.setIcon(icon2)
        self.presupuestoCancelarRegPushButton = QPushButton(nuevoPresupuestoWindow)
        self.presupuestoCancelarRegPushButton.setObjectName(u"presupuestoCancelarRegPushButton")
        self.presupuestoCancelarRegPushButton.setGeometry(QRect(350, 590, 101, 23))
        icon3 = QIcon()
        icon3.addFile(u"./assets/icons/botones/cancelar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.presupuestoCancelarRegPushButton.setIcon(icon3)
        self.presupuestoTotDolarLineEdit = QLineEdit(nuevoPresupuestoWindow)
        self.presupuestoTotDolarLineEdit.setObjectName(u"presupuestoTotDolarLineEdit")
        self.presupuestoTotDolarLineEdit.setEnabled(True)
        self.presupuestoTotDolarLineEdit.setGeometry(QRect(120, 550, 171, 20))
        self.presupuestoTotDolarLineEdit.setReadOnly(True)
        self.presupuestoTotBsLineEdit = QLineEdit(nuevoPresupuestoWindow)
        self.presupuestoTotBsLineEdit.setObjectName(u"presupuestoTotBsLineEdit")
        self.presupuestoTotBsLineEdit.setEnabled(True)
        self.presupuestoTotBsLineEdit.setGeometry(QRect(450, 550, 171, 20))
        self.presupuestoTotBsLineEdit.setReadOnly(True)

        self.retranslateUi(nuevoPresupuestoWindow)

        QMetaObject.connectSlotsByName(nuevoPresupuestoWindow)
    # setupUi

    def retranslateUi(self, nuevoPresupuestoWindow):
        nuevoPresupuestoWindow.setWindowTitle(QCoreApplication.translate("nuevoPresupuestoWindow", u"Nuevo Presupuesto", None))
        self.label.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">NUEVO PRESUPUESTO</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Fecha de Emisi\u00f3n:</p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Fecha de Vencimiento:</p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Nro. Presupuesto:</p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Cliente:</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Tasa a Utilizar (Bs):</p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Productos / Servicios:</p></body></html>", None))
        self.presupuestoNuevoAddPushButton.setText("")
        self.label_11.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p>Cantidad:</p></body></html>", None))
        self.presupuestoNuevoElimPushButton.setText("")
        self.label_8.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Total Dolares:</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Total Bol\u00edvares:</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.presupuestoAceptarRegPushButton.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u" Registrar", None))
        self.presupuestoCancelarRegPushButton.setText(QCoreApplication.translate("nuevoPresupuestoWindow", u" Cancelar", None))
    # retranslateUi

